const assert = require('node:assert/strict');
const {terrainGradient,terrainColor} = require('../../static/js/terrain-layers.js');
const fs = require('node:fs');
const path = require('node:path');
const html = fs.readFileSync(path.join(__dirname, '../../index.html'), 'utf8');
assert.equal(terrainGradient(0,1).aspect,0);
assert.equal(terrainGradient(-1,0).aspect,90);
assert.equal(terrainGradient(0,-1).aspect,180);
assert.equal(terrainGradient(1,0).aspect,270);
assert.equal(terrainGradient(1,0).slope,45);
assert.equal(terrainColor('aspect',0,0),'#a1a1aa');
assert.equal(terrainColor('aspect',Math.tan(10*Math.PI/180),0),'#a1a1aa');
assert.notEqual(terrainColor('aspect',Math.tan(10.1*Math.PI/180),0),'#a1a1aa');
assert.equal(terrainColor('slope',Math.tan(30*Math.PI/180),0),null);
assert.equal(terrainColor('slope',Math.tan(20*Math.PI/180),0),null);
assert.notEqual(terrainColor('slope',Math.tan(30.1*Math.PI/180),0),null);
assert.notEqual(terrainColor('slope',Math.tan(40*Math.PI/180),0),terrainColor('slope',Math.tan(60*Math.PI/180),0));
assert.notEqual(terrainColor('shade',1,1),terrainColor('shade',-1,-1));
assert.ok(html.includes('await cache.put(url, resp.clone())'), 'DEM tile mora biti sigurno upisan za offline rad');
assert.ok(html.includes('URL.revokeObjectURL(objectUrl)'), 'Image fallback ne smije curiti object URL memoriju');
assert.ok(html.includes("pane:'pozariPane', radius: 5"), 'simulacijske tačke moraju biti iznad projekcije plohe');
console.log('Terrain: cardinal aspects, red slope >30°, neutral threshold and hillshade passed');
