const assert = require('node:assert/strict');
const {terrainGradient,terrainColor,terrainSlopeClasses} = require('../../static/js/terrain-layers.js');
const fs = require('node:fs');
const path = require('node:path');
const html = fs.readFileSync(path.join(__dirname, '../../index.html'), 'utf8');
assert.equal(terrainGradient(0,1).aspect,0);
assert.equal(terrainGradient(-1,0).aspect,90);
assert.equal(terrainGradient(0,-1).aspect,180);
assert.equal(terrainGradient(1,0).aspect,270);
assert.equal(terrainGradient(1,0).slope,45);
assert.equal(terrainColor('aspect',0,0),'#a1a1aa');
assert.equal(terrainColor('aspect',Math.tan(10*Math.PI/180),0),'#a1a1aa');
assert.notEqual(terrainColor('aspect',Math.tan(10.1*Math.PI/180),0),'#a1a1aa');
// Pet šumarskih klasa nagiba u procentima (stepeni samo za prikaz): 0–15, 15–30, 30–50, 50–70, >70 %.
const nag = p => terrainColor('slope', p / 100, 0);
assert.equal(nag(0), '#22c55e'); assert.equal(nag(14.9), '#22c55e');
assert.equal(nag(15.1), '#facc15'); assert.equal(nag(29.9), '#facc15');
assert.equal(nag(30.1), '#f97316'); assert.equal(nag(49.9), '#f97316');
assert.equal(nag(50.1), '#dc2626'); assert.equal(nag(69.9), '#dc2626');
assert.equal(nag(70.1), '#7e22ce'); assert.equal(nag(250), '#7e22ce');
assert.equal(terrainSlopeClasses.map(k => k.label + ' ' + k.labelSt).join(' | '), '0–15 % (0–9°) | 15–30 % (9–17°) | 30–50 % (17–27°) | 50–70 % (27–35°) | >70 % (>35°)');
// Legenda na karti: između zuma i FAB-ova, iznad donje trake, ispod dugmadi po z-indexu.
const leg = html.slice(html.indexOf('#terrain-map-legend {'), html.indexOf('#terrain-map-legend .tml-title'));
assert.ok(/bottom:76px/.test(leg) && /left:70px/.test(leg) && /right:76px/.test(leg) && /z-index:590/.test(leg), 'legenda se ne smije preklapati sa dugmadima');
const tjs = fs.readFileSync(path.join(__dirname, '../../static/js/terrain-layers.js'), 'utf8');
assert.ok(tjs.includes("mapLegend.id='terrain-map-legend'") && tjs.includes("mapLegend.style.display=html?'block':'none'"), 'legenda na karti samo kad je nagib ili ekspozicija uključena');
assert.notEqual(terrainColor('shade',1,1),terrainColor('shade',-1,-1));
assert.ok(html.includes('await cache.put(url, resp.clone())'), 'DEM tile mora biti sigurno upisan za offline rad');
assert.ok(html.includes('URL.revokeObjectURL(objectUrl)'), 'Image fallback ne smije curiti object URL memoriju');
assert.ok(html.includes("pane:'pozariPane', radius: 5"), 'simulacijske tačke moraju biti iznad projekcije plohe');
console.log('Terrain: cardinal aspects, 5 slope classes, map legend, neutral threshold and hillshade passed');
